# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_feedback.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1146, 682)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/transact2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 57);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(160, 30, 801, 511))
        self.graphicsView.setStyleSheet(_fromUtf8("background-image: url(:/back/featBack.png);"))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAdd = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Impact"))
        font.setPointSize(10)
        self.menuAdd.setFont(font)
        self.menuAdd.setAutoFillBackground(False)
        self.menuAdd.setStyleSheet(_fromUtf8(""))
        self.menuAdd.setObjectName(_fromUtf8("menuAdd"))
        self.actionAddStudent = QtGui.QMenu(self.menuAdd)
        self.actionAddStudent.setObjectName(_fromUtf8("actionAddStudent"))
        self.menuStudent_Batches = QtGui.QMenu(self.menuAdd)
        self.menuStudent_Batches.setObjectName(_fromUtf8("menuStudent_Batches"))
        self.menuTransact = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Impact"))
        font.setPointSize(10)
        self.menuTransact.setFont(font)
        self.menuTransact.setObjectName(_fromUtf8("menuTransact"))
        self.menuQuery = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Impact"))
        font.setPointSize(10)
        self.menuQuery.setFont(font)
        self.menuQuery.setStyleSheet(_fromUtf8(""))
        self.menuQuery.setObjectName(_fromUtf8("menuQuery"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAddFeedback = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Impact"))
        font.setPointSize(10)
        self.actionAddFeedback.setFont(font)
        self.actionAddFeedback.setObjectName(_fromUtf8("actionAddFeedback"))
        self.actionAddCourse = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Impact"))
        font.setPointSize(10)
        self.actionAddCourse.setFont(font)
        self.actionAddCourse.setObjectName(_fromUtf8("actionAddCourse"))
        self.actionQueryFeedback = QtGui.QAction(MainWindow)
        self.actionQueryFeedback.setObjectName(_fromUtf8("actionQueryFeedback"))
        self.actionQueryCourse = QtGui.QAction(MainWindow)
        self.actionQueryCourse.setObjectName(_fromUtf8("actionQueryCourse"))
        self.actionStudent_feedback = QtGui.QAction(MainWindow)
        self.actionStudent_feedback.setIcon(icon)
        self.actionStudent_feedback.setObjectName(_fromUtf8("actionStudent_feedback"))
        self.actionStudents = QtGui.QAction(MainWindow)
        self.actionStudents.setObjectName(_fromUtf8("actionStudents"))
        self.actionModify_Feedback = QtGui.QAction(MainWindow)
        self.actionModify_Feedback.setObjectName(_fromUtf8("actionModify_Feedback"))
        self.actionSt_Add = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.actionSt_Add.setFont(font)
        self.actionSt_Add.setObjectName(_fromUtf8("actionSt_Add"))
        self.actionSt_Modify = QtGui.QAction(MainWindow)
        self.actionSt_Modify.setObjectName(_fromUtf8("actionSt_Modify"))
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionModify = QtGui.QAction(MainWindow)
        self.actionModify.setObjectName(_fromUtf8("actionModify"))
        self.actionStudent_Batches = QtGui.QAction(MainWindow)
        self.actionStudent_Batches.setObjectName(_fromUtf8("actionStudent_Batches"))
        self.actionAddBatch = QtGui.QAction(MainWindow)
        self.actionAddBatch.setObjectName(_fromUtf8("actionAddBatch"))
        self.actionModify_2 = QtGui.QAction(MainWindow)
        self.actionModify_2.setObjectName(_fromUtf8("actionModify_2"))
        self.actionModify_3 = QtGui.QAction(MainWindow)
        self.actionModify_3.setObjectName(_fromUtf8("actionModify_3"))
        self.actionStudent_Fees = QtGui.QAction(MainWindow)
        self.actionStudent_Fees.setObjectName(_fromUtf8("actionStudent_Fees"))
        self.actionAdd_Student = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/addstudent_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Student.setIcon(icon1)
        self.actionAdd_Student.setObjectName(_fromUtf8("actionAdd_Student"))
        self.actionCreate_Batch = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/batch_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Batch.setIcon(icon2)
        self.actionCreate_Batch.setObjectName(_fromUtf8("actionCreate_Batch"))
        self.actionFees = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/fee_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFees.setIcon(icon3)
        self.actionFees.setObjectName(_fromUtf8("actionFees"))
        self.actionAddStudent.addAction(self.actionSt_Add)
        self.actionAddStudent.addAction(self.actionSt_Modify)
        self.menuStudent_Batches.addAction(self.actionAddBatch)
        self.menuStudent_Batches.addAction(self.actionModify_3)
        self.menuAdd.addAction(self.actionAddFeedback)
        self.menuAdd.addAction(self.actionAddCourse)
        self.menuAdd.addAction(self.actionAddStudent.menuAction())
        self.menuAdd.addAction(self.menuStudent_Batches.menuAction())
        self.menuTransact.addAction(self.actionStudent_feedback)
        self.menuTransact.addAction(self.actionModify_Feedback)
        self.menuTransact.addAction(self.actionStudent_Fees)
        self.menuQuery.addAction(self.actionQueryFeedback)
        self.menuQuery.addAction(self.actionQueryCourse)
        self.menuQuery.addAction(self.actionStudents)
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuTransact.menuAction())
        self.menubar.addAction(self.menuQuery.menuAction())
        self.toolBar.addAction(self.actionStudent_feedback)
        self.toolBar.addAction(self.actionAdd_Student)
        self.toolBar.addAction(self.actionCreate_Batch)
        self.toolBar.addAction(self.actionFees)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "F.E.A.T.", None))
        self.menuAdd.setTitle(_translate("MainWindow", "Add", None))
        self.actionAddStudent.setTitle(_translate("MainWindow", "Student", None))
        self.menuStudent_Batches.setTitle(_translate("MainWindow", "Student Batches", None))
        self.menuTransact.setTitle(_translate("MainWindow", "Transact", None))
        self.menuQuery.setTitle(_translate("MainWindow", "Query", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar.setToolTip(_translate("MainWindow", "Student Feedback", None))
        self.actionAddFeedback.setText(_translate("MainWindow", "Feedback", None))
        self.actionAddCourse.setText(_translate("MainWindow", "Course", None))
        self.actionQueryFeedback.setText(_translate("MainWindow", "Feedback", None))
        self.actionQueryCourse.setText(_translate("MainWindow", "Course", None))
        self.actionStudent_feedback.setText(_translate("MainWindow", "Student feedback", None))
        self.actionStudents.setText(_translate("MainWindow", "Student Feedback", None))
        self.actionModify_Feedback.setText(_translate("MainWindow", "Modify Feedback", None))
        self.actionSt_Add.setText(_translate("MainWindow", "Add", None))
        self.actionSt_Modify.setText(_translate("MainWindow", "Modify", None))
        self.actionAdd.setText(_translate("MainWindow", "Add", None))
        self.actionModify.setText(_translate("MainWindow", "Modify", None))
        self.actionStudent_Batches.setText(_translate("MainWindow", "Student Batches", None))
        self.actionAddBatch.setText(_translate("MainWindow", "Add", None))
        self.actionModify_2.setText(_translate("MainWindow", "Modify", None))
        self.actionModify_3.setText(_translate("MainWindow", "Modify", None))
        self.actionStudent_Fees.setText(_translate("MainWindow", "Student Fees", None))
        self.actionAdd_Student.setText(_translate("MainWindow", "Add Student", None))
        self.actionAdd_Student.setToolTip(_translate("MainWindow", "Add Student", None))
        self.actionCreate_Batch.setText(_translate("MainWindow", "Create Batch", None))
        self.actionCreate_Batch.setToolTip(_translate("MainWindow", "Create Batch", None))
        self.actionFees.setText(_translate("MainWindow", "Fees", None))
        self.actionFees.setToolTip(_translate("MainWindow", "Student Fees", None))

import feedback_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

