# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'st_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_studentFeedback(object):
    def setupUi(self, studentFeedback):
        studentFeedback.setObjectName(_fromUtf8("studentFeedback"))
        studentFeedback.resize(995, 570)
        studentFeedback.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 57);"))
        self.centralwidget = QtGui.QWidget(studentFeedback)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 881, 541))
        self.scrollArea.setStyleSheet(_fromUtf8(""))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 879, 539))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(10, 10, 10, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setEnabled(False)
        self.checkBox.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 19, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 3, 7, 1, 1)
        self.lbl_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_6.setFont(font)
        self.lbl_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.lbl_6.setText(_fromUtf8(""))
        self.lbl_6.setObjectName(_fromUtf8("lbl_6"))
        self.gridLayout.addWidget(self.lbl_6, 11, 0, 1, 3)
        self.lbl_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_1.setFont(font)
        self.lbl_1.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.lbl_1.setText(_fromUtf8(""))
        self.lbl_1.setObjectName(_fromUtf8("lbl_1"))
        self.gridLayout.addWidget(self.lbl_1, 6, 0, 1, 3)
        self.checkBox_2 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 19, 4, 1, 5)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 2)
        self.checkBox_4 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 20, 4, 1, 5)
        self.lbl_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_3.setFont(font)
        self.lbl_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.lbl_3.setText(_fromUtf8(""))
        self.lbl_3.setObjectName(_fromUtf8("lbl_3"))
        self.gridLayout.addWidget(self.lbl_3, 8, 0, 1, 3)
        self.textEdit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 14, 1, 1, 8)
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 6)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rb_dn_4 = QtGui.QRadioButton(self.groupBox_3)
        self.rb_dn_4.setText(_fromUtf8(""))
        self.rb_dn_4.setObjectName(_fromUtf8("rb_dn_4"))
        self.horizontalLayout_3.addWidget(self.rb_dn_4)
        self.rb_d_4 = QtGui.QRadioButton(self.groupBox_3)
        self.rb_d_4.setText(_fromUtf8(""))
        self.rb_d_4.setObjectName(_fromUtf8("rb_d_4"))
        self.horizontalLayout_3.addWidget(self.rb_d_4)
        self.rb_n_4 = QtGui.QRadioButton(self.groupBox_3)
        self.rb_n_4.setText(_fromUtf8(""))
        self.rb_n_4.setObjectName(_fromUtf8("rb_n_4"))
        self.horizontalLayout_3.addWidget(self.rb_n_4)
        self.rb_a_4 = QtGui.QRadioButton(self.groupBox_3)
        self.rb_a_4.setText(_fromUtf8(""))
        self.rb_a_4.setObjectName(_fromUtf8("rb_a_4"))
        self.horizontalLayout_3.addWidget(self.rb_a_4)
        self.rb_sa_4 = QtGui.QRadioButton(self.groupBox_3)
        self.rb_sa_4.setText(_fromUtf8(""))
        self.rb_sa_4.setObjectName(_fromUtf8("rb_sa_4"))
        self.horizontalLayout_3.addWidget(self.rb_sa_4)
        self.gridLayout.addWidget(self.groupBox_3, 9, 3, 1, 6)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rb_dn_3 = QtGui.QRadioButton(self.groupBox_2)
        self.rb_dn_3.setText(_fromUtf8(""))
        self.rb_dn_3.setObjectName(_fromUtf8("rb_dn_3"))
        self.horizontalLayout_2.addWidget(self.rb_dn_3)
        self.rb_d_3 = QtGui.QRadioButton(self.groupBox_2)
        self.rb_d_3.setText(_fromUtf8(""))
        self.rb_d_3.setObjectName(_fromUtf8("rb_d_3"))
        self.horizontalLayout_2.addWidget(self.rb_d_3)
        self.rb_n_3 = QtGui.QRadioButton(self.groupBox_2)
        self.rb_n_3.setText(_fromUtf8(""))
        self.rb_n_3.setObjectName(_fromUtf8("rb_n_3"))
        self.horizontalLayout_2.addWidget(self.rb_n_3)
        self.rb_a_3 = QtGui.QRadioButton(self.groupBox_2)
        self.rb_a_3.setText(_fromUtf8(""))
        self.rb_a_3.setObjectName(_fromUtf8("rb_a_3"))
        self.horizontalLayout_2.addWidget(self.rb_a_3)
        self.rb_sa_3 = QtGui.QRadioButton(self.groupBox_2)
        self.rb_sa_3.setText(_fromUtf8(""))
        self.rb_sa_3.setObjectName(_fromUtf8("rb_sa_3"))
        self.horizontalLayout_2.addWidget(self.rb_sa_3)
        self.gridLayout.addWidget(self.groupBox_2, 8, 3, 1, 6)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rb_dn_5 = QtGui.QRadioButton(self.groupBox_6)
        self.rb_dn_5.setText(_fromUtf8(""))
        self.rb_dn_5.setObjectName(_fromUtf8("rb_dn_5"))
        self.horizontalLayout_6.addWidget(self.rb_dn_5)
        self.rb_d_5 = QtGui.QRadioButton(self.groupBox_6)
        self.rb_d_5.setText(_fromUtf8(""))
        self.rb_d_5.setObjectName(_fromUtf8("rb_d_5"))
        self.horizontalLayout_6.addWidget(self.rb_d_5)
        self.rb_n_5 = QtGui.QRadioButton(self.groupBox_6)
        self.rb_n_5.setText(_fromUtf8(""))
        self.rb_n_5.setObjectName(_fromUtf8("rb_n_5"))
        self.horizontalLayout_6.addWidget(self.rb_n_5)
        self.rb_a_5 = QtGui.QRadioButton(self.groupBox_6)
        self.rb_a_5.setText(_fromUtf8(""))
        self.rb_a_5.setObjectName(_fromUtf8("rb_a_5"))
        self.horizontalLayout_6.addWidget(self.rb_a_5)
        self.rb_sa_5 = QtGui.QRadioButton(self.groupBox_6)
        self.rb_sa_5.setText(_fromUtf8(""))
        self.rb_sa_5.setObjectName(_fromUtf8("rb_sa_5"))
        self.horizontalLayout_6.addWidget(self.rb_sa_5)
        self.gridLayout.addWidget(self.groupBox_6, 10, 3, 1, 6)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rb_dn_1 = QtGui.QRadioButton(self.groupBox)
        self.rb_dn_1.setText(_fromUtf8(""))
        self.rb_dn_1.setObjectName(_fromUtf8("rb_dn_1"))
        self.horizontalLayout.addWidget(self.rb_dn_1)
        self.rb_d_1 = QtGui.QRadioButton(self.groupBox)
        self.rb_d_1.setText(_fromUtf8(""))
        self.rb_d_1.setObjectName(_fromUtf8("rb_d_1"))
        self.horizontalLayout.addWidget(self.rb_d_1)
        self.rb_n_1 = QtGui.QRadioButton(self.groupBox)
        self.rb_n_1.setText(_fromUtf8(""))
        self.rb_n_1.setObjectName(_fromUtf8("rb_n_1"))
        self.horizontalLayout.addWidget(self.rb_n_1)
        self.rb_a_1 = QtGui.QRadioButton(self.groupBox)
        self.rb_a_1.setText(_fromUtf8(""))
        self.rb_a_1.setObjectName(_fromUtf8("rb_a_1"))
        self.horizontalLayout.addWidget(self.rb_a_1)
        self.rb_sa_1 = QtGui.QRadioButton(self.groupBox)
        self.rb_sa_1.setText(_fromUtf8(""))
        self.rb_sa_1.setObjectName(_fromUtf8("rb_sa_1"))
        self.horizontalLayout.addWidget(self.rb_sa_1)
        self.gridLayout.addWidget(self.groupBox, 6, 3, 1, 6)
        self.groupBox_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.rb_dn_2 = QtGui.QRadioButton(self.groupBox_8)
        self.rb_dn_2.setText(_fromUtf8(""))
        self.rb_dn_2.setObjectName(_fromUtf8("rb_dn_2"))
        self.horizontalLayout_8.addWidget(self.rb_dn_2)
        self.rb_d_2 = QtGui.QRadioButton(self.groupBox_8)
        self.rb_d_2.setText(_fromUtf8(""))
        self.rb_d_2.setObjectName(_fromUtf8("rb_d_2"))
        self.horizontalLayout_8.addWidget(self.rb_d_2)
        self.rb_n_2 = QtGui.QRadioButton(self.groupBox_8)
        self.rb_n_2.setText(_fromUtf8(""))
        self.rb_n_2.setObjectName(_fromUtf8("rb_n_2"))
        self.horizontalLayout_8.addWidget(self.rb_n_2)
        self.rb_a_2 = QtGui.QRadioButton(self.groupBox_8)
        self.rb_a_2.setText(_fromUtf8(""))
        self.rb_a_2.setObjectName(_fromUtf8("rb_a_2"))
        self.horizontalLayout_8.addWidget(self.rb_a_2)
        self.rb_sa_2 = QtGui.QRadioButton(self.groupBox_8)
        self.rb_sa_2.setText(_fromUtf8(""))
        self.rb_sa_2.setObjectName(_fromUtf8("rb_sa_2"))
        self.horizontalLayout_8.addWidget(self.rb_sa_2)
        self.gridLayout.addWidget(self.groupBox_8, 7, 3, 1, 6)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rb_dn_6 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_dn_6.setText(_fromUtf8(""))
        self.rb_dn_6.setObjectName(_fromUtf8("rb_dn_6"))
        self.horizontalLayout_7.addWidget(self.rb_dn_6)
        self.rb_d_6 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_d_6.setText(_fromUtf8(""))
        self.rb_d_6.setObjectName(_fromUtf8("rb_d_6"))
        self.horizontalLayout_7.addWidget(self.rb_d_6)
        self.rb_n_6 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_n_6.setText(_fromUtf8(""))
        self.rb_n_6.setObjectName(_fromUtf8("rb_n_6"))
        self.horizontalLayout_7.addWidget(self.rb_n_6)
        self.rb_a_6 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_a_6.setText(_fromUtf8(""))
        self.rb_a_6.setObjectName(_fromUtf8("rb_a_6"))
        self.horizontalLayout_7.addWidget(self.rb_a_6)
        self.rb_sa_6 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_sa_6.setText(_fromUtf8(""))
        self.rb_sa_6.setObjectName(_fromUtf8("rb_sa_6"))
        self.horizontalLayout_7.addWidget(self.rb_sa_6)
        self.gridLayout.addWidget(self.groupBox_7, 11, 3, 1, 6)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.checkBox_3 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 20, 1, 1, 2)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 18, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 3, 1, 6)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.lbl_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_5.setFont(font)
        self.lbl_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.lbl_5.setText(_fromUtf8(""))
        self.lbl_5.setObjectName(_fromUtf8("lbl_5"))
        self.gridLayout.addWidget(self.lbl_5, 10, 0, 1, 3)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 6, 1, 1)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 9)
        self.lbl_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_4.setFont(font)
        self.lbl_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.lbl_4.setText(_fromUtf8(""))
        self.lbl_4.setObjectName(_fromUtf8("lbl_4"))
        self.gridLayout.addWidget(self.lbl_4, 9, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 13, 1, 1, 8)
        self.lbl_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_2.setFont(font)
        self.lbl_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.lbl_2.setText(_fromUtf8(""))
        self.lbl_2.setObjectName(_fromUtf8("lbl_2"))
        self.gridLayout.addWidget(self.lbl_2, 7, 0, 1, 3)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 13, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout.addWidget(self.checkBox_5, 21, 1, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(910, 470, 75, 23))
        self.pushButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 500, 75, 23))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        studentFeedback.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(studentFeedback)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        studentFeedback.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(studentFeedback)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        studentFeedback.setStatusBar(self.statusbar)

        self.retranslateUi(studentFeedback)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), studentFeedback.close)
        QtCore.QMetaObject.connectSlotsByName(studentFeedback)

    def retranslateUi(self, studentFeedback):
        studentFeedback.setWindowTitle(_translate("studentFeedback", "Student Feedback", None))
        self.label_14.setText(_translate("studentFeedback", "Strongly Agree", None))
        self.label_12.setText(_translate("studentFeedback", "Neutral", None))
        self.label_3.setText(_translate("studentFeedback", "Student Name", None))
        self.label.setText(_translate("studentFeedback", "Course", None))
        self.label_11.setText(_translate("studentFeedback", "Disagree", None))
        self.label_16.setText(_translate("studentFeedback", "What other courses will you be interested in?", None))
        self.label_10.setText(_translate("studentFeedback", "Do not know", None))
        self.label_13.setText(_translate("studentFeedback", "Agree", None))
        self.label_9.setText(_translate("studentFeedback", "Please share with us how we can improve this course", None))
        self.pushButton.setText(_translate("studentFeedback", "Save", None))
        self.pushButton_2.setText(_translate("studentFeedback", "Close", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    studentFeedback = QtGui.QMainWindow()
    ui = Ui_studentFeedback()
    ui.setupUi(studentFeedback)
    studentFeedback.show()
    sys.exit(app.exec_())

