# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'st_infoentry.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(450, 629)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(209, 113, 17);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 651, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 280, 171, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 310, 281, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 340, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 180, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 210, 111, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lne_fname = QtGui.QLineEdit(self.centralwidget)
        self.lne_fname.setGeometry(QtCore.QRect(180, 110, 211, 20))
        self.lne_fname.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_fname.setObjectName(_fromUtf8("lne_fname"))
        self.lne_pname = QtGui.QLineEdit(self.centralwidget)
        self.lne_pname.setGeometry(QtCore.QRect(180, 280, 211, 20))
        self.lne_pname.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_pname.setObjectName(_fromUtf8("lne_pname"))
        self.lne_pphone = QtGui.QLineEdit(self.centralwidget)
        self.lne_pphone.setGeometry(QtCore.QRect(180, 310, 211, 20))
        self.lne_pphone.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_pphone.setObjectName(_fromUtf8("lne_pphone"))
        self.lne_pemail = QtGui.QLineEdit(self.centralwidget)
        self.lne_pemail.setGeometry(QtCore.QRect(180, 340, 211, 20))
        self.lne_pemail.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_pemail.setObjectName(_fromUtf8("lne_pemail"))
        self.lne_sphone = QtGui.QLineEdit(self.centralwidget)
        self.lne_sphone.setGeometry(QtCore.QRect(180, 180, 211, 20))
        self.lne_sphone.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_sphone.setObjectName(_fromUtf8("lne_sphone"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 210, 161, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.btn_clear = QtGui.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(50, 560, 111, 21))
        self.btn_clear.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.btn_save = QtGui.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(170, 560, 111, 21))
        self.btn_save.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 560, 111, 21))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lne_date = QtGui.QLineEdit(self.centralwidget)
        self.lne_date.setGeometry(QtCore.QRect(180, 140, 211, 20))
        self.lne_date.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_date.setReadOnly(True)
        self.lne_date.setObjectName(_fromUtf8("lne_date"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 380, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_9 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 240, 161, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 240, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lne_semail = QtGui.QLineEdit(self.centralwidget)
        self.lne_semail.setGeometry(QtCore.QRect(180, 210, 211, 20))
        self.lne_semail.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_semail.setObjectName(_fromUtf8("lne_semail"))
        self.lne_address_1 = QtGui.QTextEdit(self.centralwidget)
        self.lne_address_1.setGeometry(QtCore.QRect(180, 380, 211, 51))
        self.lne_address_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_address_1.setObjectName(_fromUtf8("lne_address_1"))
        self.lne_grade = QtGui.QLineEdit(self.centralwidget)
        self.lne_grade.setGeometry(QtCore.QRect(180, 240, 211, 20))
        self.lne_grade.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_grade.setObjectName(_fromUtf8("lne_grade"))
        self.btn_date = QtGui.QPushButton(self.centralwidget)
        self.btn_date.setGeometry(QtCore.QRect(150, 140, 16, 21))
        self.btn_date.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.btn_date.setObjectName(_fromUtf8("btn_date"))
        self.lne_address_2 = QtGui.QTextEdit(self.centralwidget)
        self.lne_address_2.setGeometry(QtCore.QRect(180, 440, 211, 51))
        self.lne_address_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_address_2.setObjectName(_fromUtf8("lne_address_2"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 440, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 500, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB Demi"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lne_zip = QtGui.QLineEdit(self.centralwidget)
        self.lne_zip.setGeometry(QtCore.QRect(180, 500, 211, 20))
        self.lne_zip.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lne_zip.setObjectName(_fromUtf8("lne_zip"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(60, 360, 331, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(60, 260, 331, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(60, 160, 331, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lne_fname, self.btn_date)
        MainWindow.setTabOrder(self.btn_date, self.lne_date)
        MainWindow.setTabOrder(self.lne_date, self.lne_sphone)
        MainWindow.setTabOrder(self.lne_sphone, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lne_semail)
        MainWindow.setTabOrder(self.lne_semail, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.lne_grade)
        MainWindow.setTabOrder(self.lne_grade, self.lne_pname)
        MainWindow.setTabOrder(self.lne_pname, self.lne_pphone)
        MainWindow.setTabOrder(self.lne_pphone, self.lne_pemail)
        MainWindow.setTabOrder(self.lne_pemail, self.lne_address_1)
        MainWindow.setTabOrder(self.lne_address_1, self.lne_address_2)
        MainWindow.setTabOrder(self.lne_address_2, self.lne_zip)
        MainWindow.setTabOrder(self.lne_zip, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.btn_save)
        MainWindow.setTabOrder(self.btn_save, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Student Information Entry", None))
        self.label_2.setText(_translate("MainWindow", "Full Name:", None))
        self.label_3.setText(_translate("MainWindow", "Parent Name:", None))
        self.label_4.setText(_translate("MainWindow", "Parent Phone:", None))
        self.label_5.setText(_translate("MainWindow", "Parent Email:", None))
        self.label_6.setText(_translate("MainWindow", "Student Phone:", None))
        self.label_7.setText(_translate("MainWindow", "Student Email:", None))
        self.btn_clear.setText(_translate("MainWindow", "Clear All", None))
        self.btn_save.setText(_translate("MainWindow", "Save", None))
        self.pushButton_3.setText(_translate("MainWindow", "Close", None))
        self.lne_date.setText(_translate("MainWindow", "Please click the button to select the date", None))
        self.label_8.setText(_translate("MainWindow", "Date:", None))
        self.label_9.setText(_translate("MainWindow", "Address (Line 1):", None))
        self.label_10.setText(_translate("MainWindow", "Grade:", None))
        self.lne_address_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.btn_date.setText(_translate("MainWindow", "...", None))
        self.lne_address_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_11.setText(_translate("MainWindow", "Address (Line 2):", None))
        self.label_12.setText(_translate("MainWindow", "Zip Code:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

